apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: hello-service
      jib: {}
  tagPolicy:
    gitCommit: {}
  local:
    push: true
deploy:
  helm:
    releases:
      - name: hello-service
        chartPath: helm/hello-service
        artifactOverrides:
          image.repository: hello-service
        setValues:
          replicaCount: "1"
    flags:
      upgrade:
        - --install
portForward:
  - resourceType: deployment
    resourceName: hello-service
    port: 8080
