apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: xylifyx/hello-service
      jib: {}
  tagPolicy:
    gitCommit: {}
deploy:
  helm:
    releases:
      - name: hello-service
        chartPath: helm/hello-service
        artifactOverrides:
          image.repository: xylifyx/hello-service
        setValues:
          replicaCount: "1"
portForward:
  - resourceType: deployment
    resourceName: hello-service
    port: 8080
