apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
    - image: xylifyx/hello-service
      jib: {}
  tagPolicy:
    gitCommit: {}
deploy:
  helm:
    releases:
      - name: hello-service
        chartPath: helm/hello-service
        artifactOverrides:
          image: xylifyx/hello-service

