name: Publish docker image
on:
  push:
    branches: ['master']
jobs:
  skaffold-build:
    name: Skaffold build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt-hotspot
      - name: Set up skaffold
        uses: yokawasa/action-setup-kube-tools@v0.8.0
        with:
          skaffold: 1.35.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish Docker images
        run: skaffold build --default-repo=ghcr.io/${{ github.repository }}
