name: Publish docker image
on:
  push:
    branches: ['master']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  skaffold-build:
    name: Skaffold build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build Docker images
        uses: hiberbee/github-action-skaffold@1.14.0
        with:
          command: build
          verbosity: trace
          repository: ${{ env.REGISTRY }}
          image: ${{ env.IMAGE_NAME }}
          tag: ${{ github.sha }}
