name: Docker build
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: ""
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # We need to fetch everything to properly get the semantic version
      - name: Version
        run: |
          version="${{ inputs.version }}"
          echo "version=${version}"
