name: Prepare Release
on:
  pull_request:
    types: closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: K-Phoen/semver-release-action
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: version
        id: version
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          version=${tag#v}
          major=${version%%.*}
          echo "::set-output name=tag::${tag}"
          echo "::set-output name=version::${version}"
          echo "::set-output name=major::${major}"
