name: Release Workflow

on:
  release:
    types: [published]

jobs:
  process-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get the release version
        run: |
          RELEASE_TAG=${{ github.event.release.tag_name }}"
          DOCKER_TAG=${RELEASE_TAG#v}
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
  docker:
    name: Docker
    needs:
      - process-release
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      version: ${{ env.DOCKER_TAG }}

