name: Release Workflow

on:
  release:
    types: [published]

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.version.outputs.docker_tag }}
    steps:
      - name: Get the release version
        run: |
          RELEASE_TAG="${{ github.event.release.tag_name }}"
          DOCKER_TAG="${RELEASE_TAG#v}"
          echo "::set-output name=docker_tag::$DOCKER_TAG"
  docker:
    name: Docker
    needs:
      - version
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      version: ${{ needs.version.outputs.docker_tag }}

