name: Release Workflow

on:
  release:
    types: [published]

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.get.outputs.docker_tag }}
    steps:
      - name: Get the release version
        id: get
        run: |
          RELEASE_TAG_NAME="${{ github.event.release.tag_name }}"
          echo docker_tag="${RELEASE_TAG_NAME#v}" >>$GITHUB_OUTPUT
  docker:
    name: Docker
    needs:
      - version
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      version: ${{ needs.version.outputs.docker_tag }}
